# Generated by Django 5.0.2 on 2024-02-20 08:25

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cap_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
