# Generated by Django 5.0.2 on 2024-02-20 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cap_app", "0002_alter_customuser_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="country",
        ),
    ]
